amostra = (input('Digite algo com tamanho de 1 a 5 caracteres: '))
print('O que foi digitado "{}" é do tipo: {}'.format(amostra, type(amostra)))
print('"{}" é um número: '.format(amostra), amostra.isnumeric())
print('"{}" é um digito: '.format(amostra), amostra.isdigit())
print('"{}" é uma letra: '.format(amostra), amostra.isalpha())
print('"{}" é maiúscula: '.format(amostra), amostra.islower())
print('"{}" é minúscula: '.format(amostra), amostra.isupper())
print('"{}" é ascii: '.format(amostra), amostra.isascii())
print('"{}" Só tem espaços: '.format(amostra), amostra.isspace())
print('"{}" É capitalizada: '.format(amostra), amostra.istitle())
